baseURL = "https://athulcyriac.xyz/"
languageCode = "en-us"
title = "Athul Cyriac Ajay"
theme = "archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="dark" # color-mode → light,dark or auto
	useCDN=true
	favicon = "https://github.com/athul.png"
[[menu.main]]
name = "Books"
url = "/books"
weight = 3

[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1

####

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"
